### ISSUE TITLE
Fails to install and run on M1 Macs because of pg_query version

### ISSUE THREAD

**Issue by AgustinBanchio** [purcell/sqlint#27]
Hi,

Unfortunately, I'm not savvy with ruby to understand how to update the pg_query version used in this linter myself.

Since we updated to M1 macbooks we had trouble running the linter

```
Could not find pg_query-1.2.0 in any of the sources
Run `bundle install` to install missing gems.
```

When trying to install we get a lot of errors. 

```
 Building native extensions. This could take a while...
ERROR:  Error installing pg_query:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/pg_query-1.2.0/ext/pg_query
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220822-64024-sb0a0l.rb extconf.rb
compiling src/pg_query.c
compiling src/pg_query_fingerprint.c
compiling src/pg_query_json.c
compiling src/pg_query_json_plpgsql.c
In file included from src/pg_query_json_plpgsql.c:2:
In file included from src/pg_query_json_plpgsql.h:5:
In file included from ./src/postgres/include/plpgsql.h:21:
In file included from ./src/postgres/include/commands/trigger.h:17:
In file included from ./src/postgres/include/nodes/execnodes.h:17:
In file included from ./src/postgres/include/access/genam.h:19:
In file included from ./src/postgres/include/nodes/tidbitmap.h:26:
In file included from ./src/postgres/include/utils/dsa.h:17:
./src/postgres/include/port/atomics.h:68:10: fatal error: 'port/atomics/arch-arm.h' file not found
#include "port/atomics/arch-arm.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/pg_query_json_plpgsql.o] Err
```

Turns out M1 Macs are compatible with pg_query 1.3.0 or later.

https://github.com/pganalyze/pg_query/issues/210

Is there a way to update the pg_query version that this linter uses?

Thanks

**Comment by purcell** [comment]
(And it's working fine for me on Apple Silicon machines.)

**Comment by arththakkar** [comment]
I am facing the same error on my MacOS 13.0

Any help?

gem 'pg_query', '2.0'

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query
/Users/arththakkar/.rvm/rubies/ruby-3.0.4/bin/ruby -I /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r ./siteconf20230106-52828-6mluz1.rb extconf.rb
creating Makefile

current directory: /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query
make DESTDIR\= clean

current directory: /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query
make DESTDIR\=
compiling /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query/guc-file.c
compiling /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query/pg_query.c
/Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query/pg_query.c:1:10: fatal error: 'pg_query.h' file not found
#include "pg_query.h"
         ^~~~~~~~~~~~
1 error generated.
make: *** [/Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0/ext/pg_query/pg_query.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/gems/pg_query-2.0.0 for inspection.
Results logged to /Users/arththakkar/.rvm/gems/ruby-3.0.4@nirvasa/extensions/x86_64-darwin-22/3.0.0/pg_query-2.0.0/gem_make.out

  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:44:in `block in make'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `each'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `make'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/arththakkar/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing pg_query (2.0.0), and Bundler cannot continue.

**Comment by 1tacticalretard** [comment]
gem install --platform=ruby --source https://rubygems.org/ sqlint

**Comment by purcell** [comment]
@1tacticalretard I don't understand the purpose of your comment. Is that a proposed solution, or are you trying to say that this command reproduces the issue above?

**Comment by 1tacticalretard** [comment]
@purcell That's a proposed solution on the issue above. Or just a workaround that was helpful for me.

**Comment by purcell** [comment]
Cool, thanks. I'm taking a look at this now.

**Comment by purcell** [comment]
The Apple-installed Ruby is 2.6, and the latest sqlint isn't compatible with that Ruby, so `gem`/`bundler` picks an older version, which then depends on an older version of `pg_query` that is not compatible with ARM MacOS.

With a newer Ruby version installed via `brew` or similar, things should generally work, except that there's currently a regression caused by the latest Xcode updates breaking compilation of the native portion of pg_query: https://github.com/pganalyze/pg_query/issues/327

**Comment by purcell** [comment]
That's all working now, and there's CI coverage for MacOS too, in case there's a regression in future.
